name: Build from depends

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  depends:
    name: depends (x86_64-linux)
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Bitcoin Repo
        uses: actions/checkout@v4
        with:
          repository: bitcoin/bitcoin
          path: bitcoin
          fetch-depth: 1

      - name: Cache Depends Sources
        uses: actions/cache@v4
        with:
          path: depends-sources
          key: depends-sources
          restore-keys: depends-sources
          enableCrossOsArchive: true

      - name: Cache Depends Built Packages
        uses: actions/cache@v4
        with:
          path: depends-base
          key: depends-base-${{ runner.os }}-${{ hashFiles('bitcoin/depends/packages/*.mk') }}
          restore-keys: depends-base-${{ runner.os }}-

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf: lazy-trees = true

      - name: Set Up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-dev-shell
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run `nix flake check`
        run: nix flake check

      - name: Build bitcoin from depends
        run: |
          nix develop --command bash -c "
            cd bitcoin
            make -C depends -j$(nproc) SOURCES_PATH=\"$PWD/depends-sources\" BASE_CACHE=\"$PWD/depends-base\"
            cmake -B build --toolchain \"$PWD/bitcoin/depends/x86_64-pc-linux-gnu/toolchain.cmake\"
            cmake --build build -j$(nproc)
          "
