name: Build from depends

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  depends:
    name: depends (x86_64-linux)
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      SOURCES_PATH: ${{ github.workspace }}/depends-sources
      BASE_CACHE: ${{ github.workspace }}/depends-base

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Checkout Bitcoin Repo
        uses: actions/checkout@v4
        with:
          repository: willcl-ark/bitcoin
          ref: cmake-dependency-provider
          path: bitcoin
          fetch-depth: 1

      - name: Set cache paths
        shell: bash
        run: |
          echo "CCACHE_DIR=${{ runner.temp }}/ccache_dir" >> $GITHUB_ENV
          echo "DEPENDS_DIR=${{ runner.temp }}/depends" >> $GITHUB_ENV
          echo "SOURCES_PATH=${{ runner.temp }}/depends/sources" >> $GITHUB_ENV
          echo "BASE_CACHE=${{ runner.temp }}/depends/built" >> $GITHUB_ENV
          echo "DEPENDS_HASH=${{ hashFiles('depends/packages/*.mk', 'depends/Makefile', 'depends/config.guess', 'depends/config.sub', 'depends/funcs.mk', 'depends/builders/*.mk', 'depends/hosts/*.mk') }}" >> $GITHUB_ENV

      - name: Cache Depends Sources
        uses: actions/cache@v4
        with:
          path: ${{ env.SOURCES_PATH }}
          key: depends-sources-${{ env.DEPENDS_HASH }}
          restore-keys: depends-sources-

      - name: Cache Depends Built Packages
        uses: actions/cache@v4
        with:
          path: ${{ env.BASE_CACHE }}
          key: depends-built-${{ github.job }}-${{ env.DEPENDS_HASH }}-${{ github.run_id }}
          restore-keys: depends-built-${{ github.job }}-${{ env.DEPENDS_HASH }}-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ github.job }}-${{ github.ref_name }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ github.job }}-

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf: lazy-trees = true

      - name: Set Up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: nix-dev-shell
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run `nix flake check`
        run: nix flake check

      - name: Build bitcoin from depends
        run: |
          nix develop --command bash -c "
            set -eux

            export CCACHE_DIR=${{ env.CCACHE_DIR }}
            export SOURCES_PATH=${{ env.SOURCES_PATH }}
            export BASE_CACHE=${{ env.BASE_CACHE }}

            cd bitcoin
            HOST_TRIPLET=\$(./depends/config.guess)
            export HOST_TRIPLET
            make -C depends -j\$(nproc) NO_QT=1
            cmake -B build --toolchain \"depends/\$HOST_TRIPLET/toolchain.cmake\" -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=\"depends/\$HOST_TRIPLET/dependency_provider.cmake\"
            cmake --build build -j\$(nproc)
            ccache --show-stats
          "
